[package]
name = "nuker"
version = "0.1.0"
authors = ["Ashrith Mekala <ashrith@cloudwick.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2.33"
colored = "1.9"
derive_more = "0.99.3"
failure = "0.1.6"
failure_derive = "0.1.6"
fern = { version = "0.5", features = ["colored"] }
humantime = "2.0.0"
humantime-serde = "1.0.0"
lazy_static = "1.4.0"
lettre = "0.9"
log = "0.4"
prettytable-rs = "0.8"
rusoto_ce = { version = "0.42", default_features = false, features = ["rustls"] }
rusoto_cloudwatch = { version = "0.42", default_features = false, features = ["rustls"] }
rusoto_core = { version = "0.42", default_features = false, features = ["rustls"] }
rusoto_credential = "0.42"
rusoto_ec2 = { version = "0.42", default_features = false, features = ["rustls"] }
rusoto_iam = { version = "0.42", default_features = false, features = ["rustls"] }
rusoto_pricing = { version = "0.42", default_features = false, features = ["rustls"] }
rusoto_rds = { version = "0.42", default_features = false, features = ["rustls"] }
rusoto_s3 = { version = "0.42", default_features = false, features = ["rustls"] }
rusoto_redshift = { version = "0.42", default_features = false, features = ["rustls"] }
rusoto_emr = { version = "0.42", default_features = false, features = ["rustls"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.5"

[dev-dependencies]
env_logger = "0.7.1"
rusoto_mock = { version = "0.42", default_features = false, features = ["rustls"] }